/* Quests. The original pulled these from /v1/mission-board; here they are
   either generated by the LLM or drawn from a built-in pool, so the feature
   survives with no server and even with no API key. */
(function (global) {
  'use strict';

  var KEY = 'ryza.quests.v1';

  /* Fallback pool, written in the game's own register. */
  var POOL = [
    { title: '朝の調合', desc: 'ライザと一緒に、今日ひとつめの調合をする。', turns: 3 },
    { title: '材料集め', desc: 'クーケン島の水源の滝つぼ周辺で、新しい材料を探す。', turns: 4 },
    { title: '冒険の準備', desc: '旅に出る前に、持って行く道具を一緒に確認する。', turns: 3 },
    { title: '思い出話', desc: 'ふたりが初めて会った日のことを、ゆっくり思い出す。', turns: 3 },
    { title: '新しいレシピ', desc: 'まだ作ったことのないレシピを、ライザと考える。', turns: 5 },
    { title: '星を見に行こう', desc: '夜のカーク群島の星見の高台まで、一緒に歩く。', turns: 4 },
    { title: '困りごと相談', desc: '最近うまくいかないことを、ライザに話してみる。', turns: 3 },
    { title: '休憩時間', desc: '調合の手を止めて、少しだけのんびり過ごす。', turns: 2 }
  ];

  var Quest = {
    items: [],

    load: function () {
      try { Quest.items = JSON.parse(localStorage.getItem(KEY) || '[]'); }
      catch (e) { Quest.items = []; }
      return Quest.items;
    },
    save: function () {
      try { localStorage.setItem(KEY, JSON.stringify(Quest.items)); } catch (e) {}
    },

    active: function () {
      return Quest.items.filter(function (q) { return !q.done; })[0] || null;
    },

    /* ---------------------------------------------------------- creation */
    create: function (useLLM) {
      if (useLLM) {
        return Api.chat([], [
          'これからライザと一緒にこなす短いお題を1つ作って。',
          '必ず次の形式だけで答えること（タグ行不要）：',
          'タイトル｜説明｜必要ターン数',
          '説明は日本語30文字以内、必要ターン数は2〜5の数字。'
        ].join('\n'), { mode: 'chat', style: 'text' }).then(function (r) {
          var m = (r.text || '').split('｜');
          if (m.length < 2) throw new Error('bad format');
          var q = {
            title: (m[0] || '').replace(/^タイトル[:：]?/, '').trim() || 'お題',
            desc: (m[1] || '').replace(/^説明[:：]?/, '').trim(),
            turns: Math.max(2, Math.min(5, parseInt(m[2], 10) || 3))
          };
          return Quest._push(q);
        }).catch(function () { return Quest._push(Quest._fromPool()); });
      }
      return Promise.resolve(Quest._push(Quest._fromPool()));
    },

    _fromPool: function () {
      return POOL[Math.floor(Math.random() * POOL.length)];
    },

    createManual: function (title, desc, turns) {
      return Quest._push({
        title: (title || '').trim() || 'お題',
        desc: (desc || '').trim(),
        turns: Math.max(2, Math.min(8, parseInt(turns, 10) || 3))
      });
    },

    _push: function (q) {
      q.id = 'q' + Date.now();
      q.progress = 0;
      q.done = false;
      q.createdAt = Date.now();
      Quest.items.unshift(q);
      if (Quest.items.length > 30) Quest.items.length = 30;
      Quest.save();
      return q;
    },

    /* One conversation turn counts as progress. */
    advance: function () {
      var q = Quest.active();
      if (!q) return null;
      q.progress++;
      if (q.progress >= q.turns) { q.done = true; q.doneAt = Date.now(); }
      Quest.save();
      return q;
    },

    remove: function (id) {
      Quest.items = Quest.items.filter(function (x) { return x.id !== id; });
      Quest.save();
    },

    clearDone: function () {
      Quest.items = Quest.items.filter(function (x) { return !x.done; });
      Quest.save();
    },

    /* --------------------------------------------------------- rendering */
    render: function (root, onTake) {
      root.innerHTML = '';
      if (!Quest.items.length) {
        root.innerHTML = '<div class="empty">' + I18n.t('quest.empty') + '</div>';
        return;
      }
      Quest.items.forEach(function (q) {
        var el = document.createElement('div');
        el.className = 'card' + (q.done ? ' done' : '');
        el.innerHTML =
          '<div class="card-title"><span class="t-title"></span>' +
          (q.done ? '<span class="tag leaf">完成</span>'
                  : '<span class="tag t-prog"></span>') + '</div>' +
          '<div class="card-sub t-desc"></div>' +
          '<div class="card-acts">' +
          (q.done ? '' : '<button class="mini-btn t-take">去完成</button>') +
          '<button class="mini-btn t-del">删除</button></div>';
        el.querySelector('.t-title').textContent = q.title;
        el.querySelector('.t-desc').textContent = q.desc;
        if (!q.done) el.querySelector('.t-prog').textContent = q.progress + '/' + q.turns;
        var take = el.querySelector('.t-take');
        take && (take.onclick = function () { onTake && onTake(q); });
        el.querySelector('.t-del').onclick = function () {
          Quest.remove(q.id); Quest.render(root, onTake);
        };
        root.appendChild(el);
      });
    },

    showClear: function (q) {
      var ov = document.getElementById('overlay-quest-clear');
      if (!ov) return;
      ov.classList.remove('hidden');
      var t = ov.querySelector('.qc-title');
      if (t) t.textContent = (q && q.title) || '';
      if (window.Sound) Sound.se('quest_clear');
      if (window.Fx) Fx.burstConfetti();
    }
  };

  var WELCOME_STEPS = [
    { id: 'talk', icon: 'icon_scroll', titleKey: 'wm.talk.title', descKey: 'wm.talk.desc' },
    { id: 'map', icon: 'icon_clock', titleKey: 'wm.map.title', descKey: 'wm.map.desc' },
    { id: 'alarm', icon: 'icon_chest', titleKey: 'wm.alarm.title', descKey: 'wm.alarm.desc' },
    { id: 'skin', icon: 'sparkle', titleKey: 'wm.skin.title', descKey: 'wm.skin.desc' },
    { id: 'quest', icon: 'icon_scroll', titleKey: 'wm.quest.title', descKey: 'wm.quest.desc' }
  ];

  var Welcome = {
    mark: function (id) {
      var w = Config.section('state').welcome || {};
      if (w[id]) return;
      Config.set('state.welcome.' + id, true);
    },
    done: function (id) {
      return !!(Config.section('state').welcome && Config.section('state').welcome[id]);
    },
    allDone: function () {
      return WELCOME_STEPS.every(function (s) { return Welcome.done(s.id); });
    },
    render: function (root) {
      root.innerHTML = '';
      var hero = document.createElement('div');
      hero.className = 'wm-hero';
      hero.innerHTML = '<h3></h3><p></p>';
      hero.querySelector('h3').textContent = I18n.t('wm.title');
      hero.querySelector('p').textContent = I18n.t('wm.sub');
      root.appendChild(hero);
      var path = document.createElement('div');
      path.className = 'wm-path';
      WELCOME_STEPS.forEach(function (s, i) {
        var done = Welcome.done(s.id);
        var tile = document.createElement('div');
        tile.className = 'wm-tile' + (done ? ' clear' : (i === 0 || Welcome.done(WELCOME_STEPS[i - 1].id) ? ' active' : ' locked'));
        var base = done ? 'tile_base_clear.svg' : (tile.className.indexOf('locked') >= 0 ? 'tile_base_locked.svg' : 'tile_base_active.svg');
        tile.innerHTML = '<img class="wm-base" alt=""><img class="wm-ico" alt=""><div class="wm-cap"></div>';
        tile.querySelector('.wm-base').src = 'assets/welcome_mission/' + base;
        tile.querySelector('.wm-ico').src = 'assets/welcome_mission/' + s.icon + '.svg';
        tile.querySelector('.wm-cap').textContent = I18n.t(s.titleKey);
        tile.title = I18n.t(s.descKey);
        tile.onclick = function () {
          if (tile.classList.contains('locked')) return;
          var dest = { talk: 'talk', map: 'world', alarm: 'alarm', skin: 'skin', quest: 'quest' };
          if (window.App) App.showView(dest[s.id] || 'talk');
        };
        path.appendChild(tile);
      });
      root.appendChild(path);
    }
  };

  global.Quest = Quest;
  global.Welcome = Welcome;
})(window);
