plugins {
    id "com.android.application"
}

android {
    namespace "com.ryza.chat"
    compileSdk 34
    defaultConfig {
        applicationId "com.ryza.chat"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
    sourceSets {
        main {
            assets.srcDirs = ["../../web"]
        }
    }
    packaging {
        resources.excludes += "**/*.md"
    }
}

dependencies {
    implementation "androidx.appcompat:appcompat:1.7.0"
    implementation "androidx.webkit:webkit:1.11.0"
}
